<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Backups\**" />
    <Content Remove="Backups\**" />
    <None Remove="Backups\**" />
    <Compile Remove="Janani.Tests\**" />
    <Content Remove="Janani.Tests\**" />
    <None Remove="Janani.Tests\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.0" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
    <PackageReference Include="Google.Cloud.Storage.V1" Version="4.10.0" />
    <PackageReference Include="Google.Cloud.PubSub.V1" Version="3.17.0" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.0" />
    <PackageReference Include="Google.Apis.Calendar.v3" Version="1.74.0.4154" />
    <PackageReference Include="Google.Apis.Gmail.v1" Version="1.74.0.3745" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection.EntityFrameworkCore" Version="8.0.0" />
    <PackageReference Include="Google.Cloud.BigQuery.V2" Version="3.9.0" />
  </ItemGroup>

</Project>
